### ISSUE TITLE
Haufenweise Fehlermeldungen 

### ISSUE THREAD

**Issue by darkdevil373** [jkbenaim/hs100#18]
Hallo ich bekomme unregelmäßig aber mehrmals täglich die folgenden Fehlermeldungen:

`instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[4]: at process.processTimers (node:internal/timers:512:7)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[4]: at listOnTimeout (node:internal/timers:569:17)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[4]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[4]: 192.168.123.105:9999 {"emeter":{"get_realtime":{}}}
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[4]: [Waschmaschine] device.send() Error: TCP Timeout after 20000ms
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[3]: at process.processTimers (node:internal/timers:512:7)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[3]: at listOnTimeout (node:internal/timers:569:17)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[3]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[3]: 192.168.123.105:9999 {"emeter":{"get_realtime":{}}}
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[3]: TCP 192.168.123.105:9999 Error: TCP Timeout after 20000ms
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[2]: at process.processTimers (node:internal/timers:512:7)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[2]: at listOnTimeout (node:internal/timers:569:17)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[2]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[2]: 192.168.123.105:9999 {"system":{"get_sysinfo":{}}}
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[2]: TCP 192.168.123.105:9999 Error: TCP Timeout after 20000ms
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[1]: at process.processTimers (node:internal/timers:512:7)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[1]: at listOnTimeout (node:internal/timers:569:17)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[1]: 192.168.123.105:9999 {"system":{"get_sysinfo":{}}}
host.iobroker-produktiv
2023-11-26 18:38:32.981	error	Caught by controller[1]: TCP 192.168.123.105:9999 Error: TCP Timeout after 20000ms

hs100.0
2023-11-26 18:38:32.937	info	terminating

hs100.0
2023-11-26 18:38:32.435	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason `

Der Adapter wurde dann von IoBroker gestoppt und muss manuell gestartet werden.

**Comment by jkbenaim** [comment]
Hallo, die Fehlermeldungen sehen so aus als ob Du das hs100-Plugin von iobroker nutzt. Diese Software hat damit nichts zu tun. Öffne doch bitte einen Bug beim hs100-Plugin selbst: https://github.com/arteck/ioBroker.hs100
